### ISSUE TITLE
I can't open hp printer device with gousb

### ISSUE THREAD

**Issue by yzzshmily** [google/gousb#107]
I have installed libusb, I can find the printer device with gousb, butI can't open the device with OpenDeviceWithVIDPID, what should I do? thanks. 

the  OpenDeviceWithVIDPID return  "Failed to compute node presentation" ,  err is nil .

**Comment by yzzshmily** [comment]
![image](https://user-images.githubusercontent.com/5506825/156524245-d9b92474-9616-49d1-a86d-705687f4ac82.png)

**Comment by zagrodzki** [comment]
This seems to be working as intended. You got back two devices. The "Failed to compute" is not an error, it's coming from your IDE.

**Comment by yzzshmily** [comment]
![image](https://user-images.githubusercontent.com/5506825/156526824-495cd8ea-ade3-4e85-8afe-0029c2cb9128.png)

**Comment by yzzshmily** [comment]
I use macos, the result is 
![image](https://user-images.githubusercontent.com/5506825/156527435-5ae1f601-6038-400c-b555-72acf1fbfbcf.png)

**Comment by oliverpool** [comment]
> If error is nil, that means *Device is not nil.

This is not true according to https://pkg.go.dev/github.com/google/gousb#Context.OpenDeviceWithVIDPID

> If none is found, it returns nil and nil error.

(sorry for necrobumping)

**Comment by zagrodzki** [comment]
> > If error is nil, that means *Device is not nil.
> 
> This is not true according to https://pkg.go.dev/github.com/google/gousb#Context.OpenDeviceWithVIDPID
> 
> > If none is found, it returns nil and nil error.

indeed, my bad, you're absolutely right. It may return (nil, nil) if no device is found.
