### ISSUE TITLE
Status of the tag v2.1.0

### ISSUE THREAD

**Issue by Hellseher** [google/gousb#124]
Hi,

The v2.1.0 was pushed 4y ago (today is <2024-03-29>), is there any plan to tag
the latest changes? I try to prepare this project for Guix but tests are failed:

```
# github.com/google/gousb [github.com/google/gousb.test]
src/github.com/google/gousb/fakelibusb_test.go:101:87: libusbContext can't be allocated in Go; it is incomplete (or unallocatable)
src/github.com/google/gousb/fakelibusb_test.go:131:10: libusbDevHandle can't be allocated in Go; it is incomplete (or unallocatable)
FAIL    github.com/google/gousb [build failed]
FAIL
```

I see the fix was merged in https://github.com/google/gousb/pull/85 <2020-11-09>
https://github.com/google/gousb/commit/0995919da423946b62bffb0522c4931773701e79

Checking dates of the tags I'm quite confused:

- <2024-02-24> :  v1.1.3 https://github.com/google/gousb/commit/2f9ed92cb863c87f7bb5fa58a54c6502ef0a5e1f
- <2022-03-29> :  v1.1.2 https://github.com/google/gousb/commit/844d4b8a718f46eb580a7a84afa00eb15c1b7a9a
- <2022-03-29> :  v1.1.1 https://github.com/google/gousb/commit/cb06b9fb0d36ba48d5b23c0299dbd1b465c3429b
- <2020-04-29> :  v2.1.0 https://github.com/google/gousb/commit/e4c3f66a1571a02d7cae859fa0be08edcb940541  <-- ? 
- <2020-04-29> :  v1.1.0 https://github.com/google/gousb/commit/e4c3f66a1571a02d7cae859fa0be08edcb940541

v1.1.0 and v2.10 is associated with the same commit, taking this may the tag
v2.1.0 be deleted?

**Comment by zagrodzki** [comment]
2.1.0 was released in error and should be ignored, see https://github.com/google/gousb/blob/master/go.mod

V1.* remains the current major version.
