### ISSUE TITLE
run gousb at Raspbian 3B(Debian)  libusb: device or resource busy [code -6]

### ISSUE THREAD

**Issue by yinhongbo** [google/gousb#22]
2017/10/18 18:35:55 vid=413c,pid=2107,bus=1,addr=5,config=1.Interface(0, 0): failed to claim interface 0 on vid=413c,pid=2107,bus=1,addr=5,config=1: libusb: device or resource busy [code -6]

**Comment by zagrodzki** [comment]
Is this a bug report? What is the bug here?

**Comment by zagrodzki** [comment]
I don't think we can do anything with this report - you didn't provide any background information and the message you've pasted looks like intended behavior, not like a bug.
