### ISSUE TITLE
Compiling for windows:amd64 failed

### ISSUE THREAD

**Issue by t33m** [google/gousb#23]
Got the error when tried compiling [this](https://gist.github.com/t33m/5ecbd754f4b5d62acee60c5bf6c46438) code for Windows amd64 platform on mac os

```sh
$ GOOS=windows GOARCH=amd64 go build -o get_usb.exe get_usb.go
# github.com/google/gousb
../../go/src/github.com/google/gousb/config.go:40:11: undefined: Milliamperes
../../go/src/github.com/google/gousb/endpoint.go:44:12: undefined: EndpointDirection
../../go/src/github.com/google/gousb/endpoint.go:48:15: undefined: TransferType
../../go/src/github.com/google/gousb/endpoint.go:54:14: undefined: IsoSyncType
../../go/src/github.com/google/gousb/endpoint.go:56:12: undefined: UsageType
../../go/src/github.com/google/gousb/interface.go:47:8: undefined: Class
../../go/src/github.com/google/gousb/interface.go:49:11: undefined: Class
../../go/src/github.com/google/gousb/interface.go:51:11: undefined: Protocol
```

P.S. 
and for linux too

**Comment by zagrodzki** [comment]
Cross-compilation with CGo won't be that simple, I'm afraid.

From https://golang.org/cmd/cgo/:

[...cgo...] is disabled by default when cross-compiling. You can control this by setting the CGO_ENABLED environment variable when running the go tool: set it to 1 to enable the use of cgo, and to 0 to disable it. The go tool will set the build constraint "cgo" if cgo is enabled.

When cross-compiling, you must specify a C cross-compiler for cgo to use. You can do this by setting the CC_FOR_TARGET environment variable when building the toolchain using make.bash, or by setting the CC environment variable any time you run the go tool. The CXX_FOR_TARGET and CXX environment variables work in a similar way for C++ code.
