### ISSUE TITLE
What is the tcdrain() equivalent in gousb?

### ISSUE THREAD

**Issue by bobvanluijt** [google/gousb#26]
Hi all,

I'm creating a simple USB lib for a device inspired by [this](http://www.robot-electronics.co.uk/files/linux_rly02.c) example in C. The code in Go is [here](https://github.com/bobvanluijt/RLY08B-controller/blob/develop/RLY08B.go).

The behavior I'm getting is that on a first run the software works fine, but on a second, third etc. It doesn't. There is no error message coming back but the command is simply not executed on the USB device.

In the C example it shows that `tcdrain()` is used. Should I add something else to close / free / flush / drain?

**Comment by zagrodzki** [comment]
I don't think this question is relevant to gousb. The example you've shown does not use gousb at all, it uses plain Go and uses device special character files for interacting through, presumably, some sort of kernel driver.

You might have more luck using some library that focuses on serial port access. I don't know of any of the libraries that do that, but a quick google search shows e.g. https://github.com/mikepb/go-serial or https://godoc.org/github.com/tarm/serial, I'm sure there's plenty more and I'm sure one of them would work for the use case you have in mind.
