### ISSUE TITLE
Can not build to windows from Ubuntu 16.04

### ISSUE THREAD

**Issue by 3mp3ri0r** [google/gousb#27]
Hi dev. I want to build apps using gousb, but I can't build it to windows environment. I've trie to build your lsusb example by using this command:
`GOOS=windows GOARCH=386 go build -o lsusbex.exe github.com/google/gousb/lsusb/main.go`
End with this message and not build:

```
# github.com/google/gousb
github.com/google/gousb/config.go:40:11: undefined: Milliamperes
github.com/google/gousb/endpoint.go:44:12: undefined: EndpointDirection
github.com/google/gousb/endpoint.go:48:15: undefined: TransferType
github.com/google/gousb/endpoint.go:54:14: undefined: IsoSyncType
github.com/google/gousb/endpoint.go:56:12: undefined: UsageType
github.com/google/gousb/interface.go:47:8: undefined: Class
github.com/google/gousb/interface.go:49:11: undefined: Class
github.com/google/gousb/interface.go:51:11: undefined: Protocol
```

I've tried to build to windows 32 and 64 bit, but got the same result.
How to build app that dependent on gousb package to windows environment from ubuntu?
Thank you.

**Comment by zagrodzki** [comment]
CGo is disabled by default when cross-compiling and needs a special configuration. See the comments in #23
