### ISSUE TITLE
libusb.h: No such file or directory

### ISSUE THREAD

**Issue by ogimenezb** [google/gousb#30]
When building

github.com\google\gousb\constants.go:18:21: fatal error: libusb.h: No such file or directory
github.com\google\gousb\libusb.go:28:20: fatal error: libusb.h: No such file or directory
github.com\google\gousb\libusb.go:28:20: fatal error: libusb.h: No such file or directory

pkg-config --cflags --libs libusb-1.0
-IC:\data\Go\include\libusb-1.0 -LC:\data\Go\lib\windows_amd64\libusb-1.0 -lusb-1.0 -Wl,-rpath -Wl,$ORIGIN

**Comment by ogimenezb** [comment]
Using a wrong pkg-config in windows, sorry about that

**Comment by DiegoLinares1964** [comment]
how do you resolved that?
