### ISSUE TITLE
libusb.pc not found

### ISSUE THREAD

**Issue by kinghunter58** [google/gousb#40]
Hi I wanted to experiment with this package, but when the main.go file of lsusb subdirectory outputs 

`# pkg-config --cflags libusb-1.0
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing 
'libusb-1.0.pc' to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
pkg-config: exit status 1
`

I extracted the [libusb](https://sourceforge.net/projects/libusb/files/libusb-1.0/) to a folder and added it to PKG_CONFIG_PATH environment variable. But then I looked and saw that there was no libusb.pc file.
I couldn't find where to find this file for download. I am on Windows 10.

**Comment by zagrodzki** [comment]
I'm not well versed in how Windows Go development works, but I think you won't be able to use gousb to build an application under vanilla Windows.

gousb will only compile within a Unix-like environment like MSYS that you must have installed before you begin. Extracting the contents of libusb source archive is definitely not enough.

Our Windows test environment uses MSYS for this (https://www.msys2.org/).
With msys you need to install (using pacman package manager):
* the compiler (mingw-w64-gcc)
* pkg-config 
* libusb (mingw-w64-gcc)
* go itself (mingw-w64-go)
and only then you can attempt to build gousb.

For reference, for testing on Windows we use AppVeyor's Visual Studio 2015 environment, see here: https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin
with this script: https://github.com/google/gousb/blob/master/.appveyor/install.sh

Hope that helps.
