### ISSUE TITLE
Build error Windows

### ISSUE THREAD

**Issue by Doskulov** [google/gousb#66]
Hello, when building to windows executable file, returns error. When not using gousb library, works fine.
`CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build -o index.exe`

Error Type
`github.com/google/gousb`
`collect2: error: ld returned 1 exit status`

**Comment by zagrodzki** [comment]
I don't think we can help with this problem. Our windows build seems to be running fine - see https://ci.appveyor.com/project/zagrodzki/gousb/history
