### ISSUE TITLE
(*gousb.InEndpoint) Read() violates io.Reader contract

### ISSUE THREAD

**Issue by alexpevzner** [google/gousb#76]
Using input buffer size which is not multiple of USB packet size with the (*gousb.InEndpoint) Read() may cause LIBUSB_TRANSFER_OVERFLOW:

http://libusb.sourceforge.net/api-1.0/libusb_packetoverflow.html

But io.Reader interface definition doesn't contain such a limitation. It is unlikely that this behaviour can be fixed, so please at least document it.

**Comment by zagrodzki** [comment]
Documented.
