### ISSUE TITLE
Writing 20M buffer to output endpoint return error

### ISSUE THREAD

**Issue by nandra** [google/gousb#80]
Hi,

I'm using gousb on hos tPC to send some dummy data to custom USB device. I'm basically sending files. I find out that 12M file can be written to output endpoint but 20M file return:
```
Write returned an error: libusb: i/o error [code -1]
```
Is there some limit in data buffer which can be sent or am I doing something wrong? I'm using same code as example in this repo. Thanks.

**Comment by zagrodzki** [comment]
The error is returned by libusb, so it's likely not related to gousb. You can try to enable libusb debugging (http://libusb.sourceforge.net/api-1.0/#msglog) or use something like wireshark to capture the traffic on the usb bus to see the reason. There are no limitations on buffer sizes on gousb side.
