### ISSUE TITLE
ERROR: Unknown revision v2.1.0

### ISSUE THREAD

**Issue by HeinzAlberto** [google/gousb#83]
Hi there!

 When installing gousb using 
"go get -v github.com/google/gousb" (as written in the Readme on GitHub) I just get the error "go: error loading module requirements"...
(See screenshot.)

Is there a workaround for this problem?
![grafik](https://user-images.githubusercontent.com/18151901/95909969-a5f21900-0d9f-11eb-933e-d83b4d5e903b.png)

**Comment by zagrodzki** [comment]
Argh. The go proxy (proxy.golang.org) cached the info about v2.1.0, and apparently there's no way to remove it, even though it was present only for one day in April. Sad face.
I've reinstated the v2.1.0.

**Comment by zagrodzki** [comment]
FTR, we've released v1.1.1 with a module specification (`go.mod `) and I believe `go get` will prefer that over the v2.1.0+incompatible from now on.
