### ISSUE TITLE
 Failed to claim interface 0

### ISSUE THREAD

**Issue by wimmerX** [google/gousb#88]
Question: `2021/01/07 14:58:44 vid=25a7,pid=fa23,bus=1,addr=40.DefaultInterface(): failed to claim interface 0 on vid=25a7,pid=fa23,bus=1,addr=40,config=1: libusb: not found [code -5]`
OS :5.4.85-1-ARCHLINUX #1 SMP PREEMPT Mon Dec 21 21:38:53 UTC 2020 x86_64 GNU/Linux
Others:it can read usb configuration and interface information, but cannot claim.So what can I do to deal with it.Thanks.XD..

**Comment by zagrodzki** [comment]
This is likely unrelated to `gousb` and more related to the specifics of the device that you're interacting with. libusb error suggests that the device in this configuration doesn't have the interface 0. Look into the output of `lsusb -v` for details.
