### ISSUE TITLE
Memory Leak in CGO part

### ISSUE THREAD

**Issue by danielPaulusMesmer** [google/gousb#96]
Hey, @zagrodzki 
I have a memory leak in my app using gousb. There is nothing in pprof so I assume it is somewhere in the CGO parts.
Do you have any advice how to figure out where the leak is?

**Comment by zagrodzki** [comment]
I don't have any specific advice. If you can build a small repro case that I can run myself, then I could take a look, but otherwise, I don't think I can be of much help here.
